### ISSUE TITLE
Лабораторная 1

### ISSUE THREAD

**Issue by SvetaTrusova** [SvetaTrusova/algorithms-and-data-structures#2]
@anton0afanasiev0v Здравствуйте, закончила ЛР1 с оформлением, у меня есть проблемы с запуском тестов через терминал(он как будто не распознает * при передачи пути), но из самого файла с тестами все работает.

**Comment by anton0afanasiev0v** [comment]
Если это не актуально, тогда закрой задачу. Иначе напиши, что актуально
