### ISSUE TITLE
Лабораторная 1

### ISSUE THREAD

**Issue by SvetaTrusova** [SvetaTrusova/algorithms-and-data-structures#3]
Здравствуйте, сделала структуру 1й лабы справками по коду, которые с вами обсуждали. Все тесты запускаются через файлы run_tests и run_tasks

**Comment by anton0afanasiev0v** [comment]
Оставил кометы, поправь их. И делай следующие. На комменты ты тоже можешь отвечать и отмечать, что их сделала 
https://github.com/SvetaTrusova/algorithms-and-data-structures/pull/1

**Comment by anton0afanasiev0v** [comment]
Молодец. В целом это уже отлично)
